pins.A0.digitalWrite(false)
pins.A1.digitalWrite(false)
pins.A2.digitalWrite(false)
pins.A3.digitalWrite(false)
forever(function () {
    pins.A1.servoWrite(20)
    pins.A2.servoWrite(145)
    pause(500)
    pins.A1.digitalWrite(false)
    pins.A2.digitalWrite(false)
    pause(500)
    // A0 and A3 are servo select pins
    pins.A0.digitalWrite(true)
    pins.A3.digitalWrite(true)
    pause(500)
    pins.A1.servoWrite(151)
    pins.A2.servoWrite(30)
    pause(500)
    pins.A1.digitalWrite(false)
    pins.A2.digitalWrite(false)
    pins.A0.digitalWrite(false)
    pins.A3.digitalWrite(false)
})
